disallowed-names = ["binding", ".."]
disallowed-macros = ["cmd_lib::run_cmd", "cmd_lib::run_fun"]
check-private-items = true                                   # recommended?
enforce-iter-loop-reborrow = true
excessive-nesting-threshold = 5
