category: Productivity
choices:
  - name: LibreOffice
    provider: The Document Foundation
    description: |
      LibreOffice is an open source office suite. It features applications like a word processor, presentation builder,
      spreadsheet tool, and more. It's compatible with all Microsoft Office files.
    options:
      - checkbox: flatpak
    actions:
      - rpm:libreoffice
      - flatpak:org.libreoffice.LibreOffice

  - name: OnlyOffice
    provider: ONLYOFFICE
    description: OnlyOffice is an office suite designed to behave like Microsoft Office, with familiar design and collaboration features.
    actions: flatpak:org.onlyoffice.desktopeditors

  - name: Evolution
    provider: The GNOME Project
    editions: [gnome, flagship, xfce]
    description: Evolution is a powerful personal information manager and email client with support for IMAP, POP3, and Exchange.
    options:
      - checkbox: flatpak
    actions:
      - rpm:evolution
      - flatpak:org.gnome.Evolution

  - name: Merkuro
    provider: KDE
    editions: [plasma]
    description: An application suite designed to make handling your emails, calendars, contacts, and tasks simple.
    actions: rpm:merkuro

  - name: Notejot
    provider: Lainsce
    description: A stupidly-simple notes application for any type of short term notes or ideas.
    actions: flatpak:io.github.lainsce.Notejot

  - name: Rnote
    provider: Flxzt
    description: Rnote is a versatile note-taking app with infinite pages and PDF imports.
    options:
      - checkbox: flatpak
    actions:
      - rpm:rnote
      - flatpak:com.github.flxzt.rnote

  - name: Folio
    provider: Greg Ross/Toolstack
    description: A beautiful markdown note-taking app.
    options:
      - checkbox: flatpak
    actions:
      - rpm:folio
      - flatpak:com.toolstack.Folio

  - name: Foliate
    provider: John Factotum
    description: Modern e-book reader.
    options:
      - checkbox: flatpak
    actions:
      - rpm:foliate
      - flatpak:com.github.johnfactotum.Foliate

  - name: PDF Arranger
    provider: The PDF Arranger Team
    description: A small application, which helps the user to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface.
    actions: flatpak:com.github.jeromerobert.pdfarranger